name: de-sar-sample-data
channels:
- conda-forge
- nodefaults
dependencies:
- python >=3.13.3,<3.14
- ipykernel >=6.29.5,<7
- odc-stac *
- pystac-client >=0.8.6,<0.9
- numpy >=2.2.5,<3
- folium >=0.19.5,<0.20
- botocore >=1.38.15,<2
- matplotlib >=3.10.3,<4
- scipy >=1.15.2,<2
- geopandas >=1.1.1,<2
- pip
- pip:
  - rustac>=0.8.1, <0.9
